# Generated by Django 5.1.1 on 2024-09-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyectos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tamano', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('id_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.entregable')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_asig_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='Usuarios.usuario')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.estado')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='entregable',
            name='id_tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea'),
        ),
        migrations.CreateModel(
            name='TareaAsignacion',
            fields=[
                ('id_asig_t', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
    ]
