services:
  api:
    build: ./App
    container_name: ah_promanage_web
    ports:
      - 8022:8022
    environment:
      DB_NAME: Promanage  
      DB_HOST: db  
      DB_PORT: 7012  
      DB_USER: Soporte 
      DB_PASSWORD: 1522  
    depends_on:
      - db  
    volumes:
      - ./App/Frontend:/App/Frontend  
    networks:
      - ag

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: Soporte
      POSTGRES_PASSWORD: 1522
      POSTGRES_DB: Promanage
    ports:
      - 7012:5432
    networks:
      - ag

networks:
  ag: 
    external : true


   
 

