services:
  api:
    build: ./api
    container_name: ah_promanage_web
    ports:
      - 8022:8022
    environment:
      DB_NAME: railway
      DB_HOST: autorack.proxy.rlwy.net
      DB_PORT: 52744
      DB_USER: postgres
      DB_PASSWORD: KTONJqnAteMSScvyyolzAhfIrBZIeAIX
    networks:
      - ag 

  
networks:
  ag:
    external: true