services:
  api:
    build: ./api
    container_name: fastapi-container
    ports:
      - "8000:8000"
    environment:
      DB_NAME: railway
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: KTONJqnAteMSScvyyolzAhfIrBZIeAIX
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KTONJqnAteMSScvyyolzAhfIrBZIeAIX
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
