

services:
  api:
    build: .
    container_name: fastapi-container
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=railway
      - DB_HOST=autorack.proxy.rlwy.net
      - DB_PORT=52744
      - DB_USER=postgres
      - DB_PASSWORD=KTONJqnAteMSScvyyolzAhfIrBZIeAIX







