# Generated by Django 5.1.1 on 2024-09-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('id_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados', to='Usuarios.usuario')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.estado')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoAsignacion',
            fields=[
                ('id_asig', models.AutoField(primary_key=True, serialize=False)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyecto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
    ]
